spring.application.name=shr
server.port=7001

gofr.openhim.url=http://192.168.19.152:5001/fhir/DEFAULT
gofr.openhim.clientid.password.basic.auth=fhir:Admin123

opencr.openhim.url=http://192.168.19.153:8080/hapi-fhir-jpaserver/fhir
opencr.openhim.clientid.password.basic.auth=openmrs:Admin123

CENTRAL.FHIR=http://intelehealth-central-fhir.mpower-social.com/hapi-fhir-jpaserver/fhir