spring.application.name=shr
server.port=7001

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/opensrphatraining
#spring.datasource.username=opensrp_admin
#spring.datasource.password=admin
#spring.jpa.database-platform=postgres
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
#spring.jpa.show-sql=true



gofr.openhim.url=http://192.168.19.152:5001/fhir/DEFAULT
gofr.openhim.clientid.password.basic.auth=fhir:Admin123
opencr.openhim.url=http://192.168.19.153:8080/hapi-fhir-jpaserver/fhir
opencr.openhim.clientid.password.basic.auth=openmrs:Admin123
MPI.CODING=7405fe34-a4e3-4705-b876-ece59cb6aa18
CENTRAL.FHIR=http://intelehealth-central-fhir.mpower-social.com/hapi-fhir-jpaserver/fhir